### ISSUE TITLE
Asynchronous Image Fetching

### ISSUE THREAD

**Issue by Kdcarrero** [Kdcarrero/Snippet#9]
In the MainWindow_Activity there is a commented out AsyncTask class that attempts to handle image fetching. The issue is that it tries to update the RecyclerView's adapters which isn't allowed due to it being different from the UI thread.

Without async fetching the app takes forever to process the photos.

**Comment by Kdcarrero** [comment]
App crashes with the error "android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views."

**Comment by bqh1112** [comment]
This didn't happen when I ran it, I think. I'll take another look.

**Comment by Kdcarrero** [comment]
I'm testing my fix now. Apparently the onPostExecute function in the Async task runs on the UI thread

**Comment by Kdcarrero** [comment]
fixed it. I'm going to try and speed up the process of getting pictures to the view next.
